name: testing workflow variables

on:
  workflow_dispatch:

env:
  cloud: aws-cloud

jobs:
  greeting_job:
     runs-on: ubuntu-latest
     env:
       Greeting: hello
     steps:
       - name: "Say Hello world it's Monday"
         run: echo "$Greeting $First_Name is using $cloud"
         env:
           First_Name: Rahul Kumthekar
